package.json

Updated to babel-plugin-react-transform 2.0.0 instead of 2.0.0-beta1
Thx @thejameskyle @gaearon

babel-plugin-react-transform 2.0.0 is out of beta

---

webpack/webpack.base.babel.js

Brings the correct query so react-transform can hot-reload components properly.

Fix typo in Babel Loader for Hot-Reload

---

app/app.js
app/components/Button/Button.react.js
app/components/Button/Button.test.js
app/containers/HomePage/HomePage.react.js
app/containers/ReadmePage/ReadmePage.react.js
app/rootReducer.js
package.json

I sent [#88](https://github.com/mxstbr/react-boilerplate/pull/88) which I combined the repo with  [redux-simple-router](https://github.com/rackt/redux-simple-router) a few days ago.
Sorry for sending the new PR late , because I had busy weekend for the past two day. There are two main points about the new PR.
1. Add the [redux-simple-router](https://github.com/rackt/redux-simple-router) like what I did in [#88](https://github.com/mxstbr/react-boilerplate/pull/88)
2. Extract component methods(`onChangeProjectName` ,  `onChangeOwnerName` ...) from `HomePage` component. I think this made **Presentational Components** (`HomePage` , `ReadmePage`) more "PURE" and clear. Then, export Container components **connect()-ed**  to Redux by means of `mapDispatchToProps` and `mapStateToProps` suggested …

update Container Component and add redux-simple-router

---

app/components/Button/Button.test.js

Pass a function instead of a string to avoid warning.

Fix warning for handleRoute prop

---

.stylelintrc
app/components/Anchor/styles.css
app/components/Button/styles.css
app/components/Footer/styles.css
app/components/Heading1/styles.css
app/components/Heading2/styles.css
app/containers/App/styles.css
app/containers/HomePage/styles.css
app/containers/ReadmePage/styles.css
docs/general/commands.md
package.json

created: 
- .stylelintrc
updated: 
- CSS files to 4 spaces
- Linting commands
- npm run lint, npm run lint:js, npm run lint:css 
- note I added "|| true" to avoid an Exit 2 npm occurrence on CSS lint:    https://github.com/npm/npm/issues/6124
- docs/general/commands.md

Styelint for CSS with CLI configuration

---

.travis.yml
README.md
package.json

Implement Coveralls task & badge.

---

package.json

[`--progress` breaks deployment on Heroku](https://github.com/webpack/webpack/issues/1553)
Not sure how everyone's deploying their projects and what you're checking in etc but I've added `"postinstall": "npm run build"` to my package.json; kinda annoying not being able to build on a server!
Is this generalized enough to add as a default?

Remove webpack --progress from build script

---

internals/generators/container/index.js
internals/generators/container/index.js.hbs

In a default install of v3.0.0 (cloned about 15 minutes ago), generating a new Container and then attempting to require it on the homepage throws the following error (assuming the Container is named `LoginForm`).
```
./app/containers/LoginForm/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./login-form.css in [localpath]/app/containers/LoginForm
resolve file
[localpath]/app/containers/LoginForm/login-form.css doesn't exist
[localpath]/app/containers/LoginForm/login-form.css.js doesn't exist
[localpath]/app/containers/LoginForm/login-form.css.jsx doesn't exist
[localpath]/app/containers/LoginForm/login-form.css.react.js doesn't exist
resolve directory
[localpath]/app/containers/LoginForm/login-form.css/package.json doesn't exist (directory description file) …
```

Container Generator requires CSS file that is not created

---

.gitattributes

Added `eol=lf` to *.js files in .gitattributes, see issue #249

Added line ending settings for *.js files in .gitattributes

---

package.json

Duplicated sanitize.css on dependencies and devDependencies.
Remove the warning: `npm WARN package.json Dependency 'sanitize.css' exists in both dependencies and devDependencies, using 'sanitize.css@^3.3.0' from dependencies`

Remove sanitize.css from devDependencies

---

internals/webpack/webpack.base.babel.js
internals/webpack/webpack.prod.babel.js
internals/webpack/webpack.test.babel.js

In dev and test phases, NODE_ENV was not correctly set and use of `process.env.NODE_ENV` always returned `undefined` in app code execution.
Config for prod was put together with dev in webpack.base.babel.js 
#301

Fix webpack config for NODE_ENV use in code

---

internals/webpack/webpack.base.babel.js

While trying to integrate Semantic UI to this boilerplate, I noticed that the webpack config was missing file loaders for font files and svg files used by semantic-ui. I thought it could be usefull to others so I thought I'd share it. 
Found the fix in this thread https://github.com/Semantic-Org/Semantic-UI/issues/3533
Not included in the PR since it's very specific to semantic-ui : 
One other thing I had to do to make it work was to include / exclude semantic css in the `webpack.base.babel.js` file like so : 
```javascript
{
// Transform our own .css files with PostCSS and CSS-modules
test: /\.css$/,
exclude: [/node_modules/, /semantic/],
loader: options.cssLoaders,
}, {
test: /\.css$/,
include: [/node_modules/, /semantic/],
loaders: ['style-loader', 'css-loader'],
}, 
```
Then in my …

Added missing loaders for fonts files and svg

---

README.md

The term "DX" is used in the README, but it is not explained anywhere. This PR adds "DX (Developer eXperience)", so readers unfamiliar with the term will immediately understand its meaning.
https://github.com/mxstbr/react-boilerplate/issues/313

Add meaning of "DX". Fix #313

---

docs/general/faq.md

Because the process for killing an existing server is identical in Linux and OSX, this change adds " / Linux" to the subheader in this section.
(A small change, but I felt it was worth a note.)

Adds "Linux" to line 18 of docs/general/faq.md 

---

package.json

| Name | Build size impact | Description |
|:-----|:-----|:------|
| [transform-react-constant-elements](https://babeljs.io/docs/plugins/transform-react-constant-elements/) | +0.032 kB | Save some memory allocation. |
| [transform-react-inline-elements](https://babeljs.io/docs/plugins/transform-react-inline-elements//) | +5.5 kB | Improve runtime performance. |
| [transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) *(Promoted)* | -1.5 kB | Remove the `propTypes`. | 
Read [Improve React performance with Babel](https://medium.com/doctolib-engineering/improve-react-performance-with-babel-16f1becfaa25) for more details.

[Babel] Improve perf of the production build

---

internals/generators/container/index.js.hbs
internals/generators/container/reducer.test.js.hbs
internals/generators/container/selectors.js.hbs

Following discussion in #337, I rewrote container and selectors templates :
- added comments to explain all of these selectors, mapStateToProps stuff
- simplify code in container template to use the default selector defined in selector.js, inside connect. All selector stuff is now in selectors.js
I also fixed an issue in reducer.test.js

Update container and selectors templates 

---

internals/webpack/webpack.prod.babel.js

* Remove `relativePaths: true` because it's `true` by default
* Add `safeToUseOptionalCaches: true` to remove warnings about additional caches
* Make AppCache cache both sections: `main` and `additional`

OfflinePlugin fixes and improvments

---

internals/generators/container/selectors.js.hbs

Related to this issue: https://github.com/mxstbr/react-boilerplate/issues/337

Fix selectors generator to not show an error message by default

---

docs/general/commands.md

Readme should be `npm run start` instead of `npm run serve`

Fix wrong command on CLI readme for pagespeed

---

app/store.js
internals/templates/store.js

regarding #379 - 
- fixes issue pointed out by @saschatimme
- switches from legacy require.ensure to system loader
however i was not able to get this working with async reducers (yet)... i have several projects working with vanilla webpack HMR (and async reducers), but they not using react-transform or webpack v2
basically, with async imports the dependency graph requires instrumenting module.hot at the root to accept routes.js to rebuild... as @tsm91 pointed out in his console log:
```
[HMR] Updated modules:
[HMR]  - ./app/containers/HomePage/reducer.js
[HMR]  - ./app/routes.js
[HMR]  - ./app/app.js    <--- needs to capture update and re-render routes
```
can be resolved using vanilla hmr, but local component state will be lost on reloads. this also might be solved with react-hot-loader …

Fix HMR for sync reducers

---

internals/webpack/webpack.dev.babel.js

rationale: since inline-source-map generates 1:1 line-column mappings it is much more expensive to generate... dev mode can use cheap-module-eval-source-map algorithm as it provides huge performance gains by only mapping the line numbers from original source
@mxstbr this change has been removed from intl PR :)

Update to more performant source mapping

---

internals/scripts/clean.js
internals/templates/routes.js

Trivial edit, pages exist as containers prior to running `clean`
The changes are as follows:
* Copy from `templates/` to `containers/` when running `clean` for:
* HomePage/
* NotFoundPage/
* Edit to internals/templates/routes.js to import Pages from containers/

Move pages created with clean script to containers

---

internals/scripts/setup.js

Following commit 80da0c5, npm run clean fails on new clones. This PR reverts those changes so that new users can install the project acceptably. The issue is discussed here https://github.com/mxstbr/react-boilerplate/issues/433

Undo commit 80da0c5 which caused npm run clean to fail

---

server/middlewares/frontendMiddleware.js

When there's an error in development such as an invalid import, Webpack likes to spam the terminal with a bunch of (as far as I can tell) useless stuff:
This pull request causes the useless spam to be excluded.

Don't let Webpack spam the terminal on errors

---

app/containers/App/styles.css

Since we use cssnext [1], we don't need to write these prefixes
ourselves. Cssnext includes autoprefixer [2], which will automatically
add the necessary prefixes.
[1] http://cssnext.io/
[2] http://cssnext.io/features/#automatic-vendor-prefixes

Remove prefixed CSS from our source code.

---

docs/general/faq.md

Defining font-faces in App/styles.css imports fonts into webpack but somehow the fonts cannot load properly in development, they work fine however when you build it.
Solution is to add an absolute output.publicPath in webpack.dev.babel.js, with protocol. i.e 'http://127.0.0.1:3000/'
#443

Added FAQ for using local webfonts in development mode.

---

internals/generators/container/index.js.hbs

Modifies internals/generators/container/index.js.hbs with:
* if statment wrapped around selector include
* if and if-else wrapped around mapSateToProps add
If these are added and no selector is generated, this error is thrown: `Module not found: Error: Can't resolve './selectors`

Add if and if-else to container to link selector

---

internals/testing/karma.conf.js

Does the same as #414, but for tests.

Hide Webpack terminal spam on test errors

---

server/index.js

To run the app on a custom port number (e.g. 5000), execute:
npm start -- -p 5000

changing default port number from cmd arguments

---

internals/webpack/webpack.base.babel.js

webm and mp4 were both using video/mp4 as mimetype. I've added a seperate loader for webm.

Fixed webm mimetype

---

docs/general/commands.md
internals/testing/karma.conf.js
package.json

This allows the use of `npm run test -- --grep ComponentName`

Allow use of Mocha grep option

---

docs/README.md

The documents in `general` were not linked correctly from `README.md`.

fixed links to docs in general

---

internals/webpack/webpack.base.babel.js

A small fix that simply ensures webpack's CommonsChunkPlugin to generate a `common.js` bundle instead of `common.js.js`.

Rename `common.js` to `common` since CommonsChunkPlugin auto-appends `.js`

---

app/app.js

If you use Redux devTools extension, since v2.0.1, they added an `updateStore`, so any enhancer that changes the store object could be used with the devTools' store.
As this boilerplate uses Redux and Redux-Saga, the `updateStore` is needed if you want to `take` actions in your Sagas, dispatched from devTools.
For more information, refer to the [release v2.0.1][release].
[release]: https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.1

Update Redux dev-tools extension's store

---

app/components/A/index.js
app/components/H1/index.js
app/components/H2/index.js
app/components/H3/index.js

react/jsx-curly-spacing was not respected in some places.
```
... /react-boilerplate/app/components/A/index.js
15:7   error  There should be no space after '{'   react/jsx-curly-spacing
15:18  error  There should be no space before '}'  react/jsx-curly-spacing
... /react-boilerplate/app/components/H1/index.js
7:37  error  There should be no space after '{'   react/jsx-curly-spacing
7:48  error  There should be no space before '}'  react/jsx-curly-spacing
... /react-boilerplate/app/components/H2/index.js
7:37  error  There should be no space after '{'   react/jsx-curly-spacing
7:48  error  There should be no space before '}'  react/jsx-curly-spacing
... /react-boilerplate/app/components/H3/index.js
5:9   error  There should be no space after '{'   react/jsx-curly-spacing
5:20  error  There …
```

Fix eslint errors

---

app/app.js

Changed the loader for manifest.json from json-loader to file-loader
to prevent it being wrapped with module.exports
Used approach as described here:
https://github.com/webpack/webpack/issues/1747#issuecomment-164561113
Fixes #580

Manifest.json formatting fix

---

package.json

Updated lint-staged to the latest version that supports npm run tasks. Added `lint:eslint` task without paths that is used by `lint:js` and `lint-staged` to properly ignore files.

Do not run lint-staged on ignored files

---

app/routes.js
app/utils/asyncInjectors.js
app/utils/tests/asyncInjectors.test.js
internals/scripts/clean.js
internals/templates/asyncInjectors.js
internals/templates/asyncInjectors.test.js
internals/templates/routes.js

I'm a naming freak and I don't think `hooks` say much about what are those functions and this file. So, sometime ago I've renamed it in my project, and now I'm porting it here so you guys can choose if you want to merge it.
-
BTW, thanks for the awesome project, it helped me a lot to grasp all those libraries and plugins.

Rename utils/hooks to asyncInjectors

---

internals/templates/app.js

Template of app.js is missing "!" when importing manifest.json - it makes manifest wrongly served and this not working after "npm start".

Missing "!" in app.js (template) manifest import

---

docs/js/routing.md

As promised, here is an example of how to use childRoutes in `routes.js`. See https://github.com/mxstbr/react-boilerplate/issues/499#issuecomment-230145069

Include `childRoutes` example

---

docs/general/faq.md

the publicPath needs to end with a /, else the main.js file returns the content of index.html

add trailing slash to publicPath in faq

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

should make maintenance a little easier... direct library questions to stack overflow, encourage searching closed issues, remind people to update code generators in prs, write tests, etc

chore(repo): GitHub templates for issues/pull requests

---

internals/generators/route/index.js
internals/generators/route/route.hbs

Fixes #765 
Added component name to a route without a reducer.
The blank lines were caused by a trailing whitespace at the end of the template file. Removing it sorted the issues with the blank lines.

Assign name to reducer-less routes. Fix blank line bug.

---

docs/general/faq.md

As proposed by @mxstbr in #696 : add instructions to support of bitbucket pipelines in the FAQ rather than directly in the repo

Add instructions for bitbucket pipelines support

---

internals/templates/app.js

After user run `npm run clean`
The clean project didn't implement polyfill for safari browser
and make the website unrendered.

fix(intl): polyfill for safari when clean the sample project

---

internals/webpack/webpack.prod.babel.js

Disabling based on #450 and the fact that it’s depreciated: _https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache_
Also this would technically solve #779

Disable AppCache generation

---

package.json

`minimist` has been defined twice, in both dependencies and devDependencies. The one in the dependencies got removed.
---

Delete a duplicate dependency

---

app/app.js
internals/generators/language/polyfill-intl-locale.hbs

Old code in `Promisel.all([])` create racing condition bug when `intl` get import AFTER the others.
Fix it by using `Promise()` and make them to get called in order.
(p.s. i've no idea why my pull request is mess up, many commits shown, please feel free to advise how can i make it better, thank you.)

racing condition when polyfill intl in old browser

---

internals/webpack/webpack.prod.babel.js

When i set `cssnext` to support browser `Safari >= 8`
it expect to prefix `webkit` for some styles.
It's already work properly in dev environment
but not in production environment.
After reading this issue
https://github.com/postcss/autoprefixer/issues/660
it suppose to add `&-autoprefixer` in `css-loader` parameter
So, i add a pull request here.

fix(webpack): webkit prefix get disappear because of uglifyjs

---

app/components/Button/index.js
app/containers/App/index.js
app/containers/LanguageProvider/index.js
docs/testing/component-testing.md
internals/templates/appContainer.js
internals/templates/languageProvider/languageProvider.js

Use [React.Children](https://facebook.github.io/react/docs/top-level-api.html#react.children) to manage opaque data structures passed to `props.children`

chore(core): Use React.Children to manage opaque prop data

---

app/containers/LanguageProvider/index.js

removes unnecessary `mapDispatchToProps` from `LanguageProvider` container

fix(containers): Remove unnecessary param from LanguageProvider

---

internals/webpack/webpack.base.babel.js
package.json

Since the latest release of `babel-core` and `babel-preset-2015` (6.13.2) can handle presets options.
No longer need to use `babel-preset-es2015-webpack`
Thanks goes to @zoontek on https://github.com/gajus/babel-preset-es2015-webpack/issues/14#issuecomment-237869435

Feature/remove babel-preset-es2015-webpack

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

**Please open an issue** before embarking on any significant pull request, expecially those that …

Fixed linking to LICENSE.md in GitHub templates

---

internals/scripts/clean.js
internals/testing/test-bundler.js

When `npm run clean` was executed, it copied `store.test.js` to `/app/store.test.js` instead of the original location in the `tests` folder. A simple path change in `clean.js` took care of it. 
This one is a bit tricky, and  I would love to have some input. Currently, there is a regex inside 
`test-bundler.js` that avoids coverage for `store.js`. This regex also captures the `store.test.js` file inside the tests folder. I assumed that since we have a test for the store.js file, it would also need to be included in the coverage. So, the regex was modified to remove `store`.

fixing store.test.js file duplication and test execution

---

package.json

The version of lint-staged was changed from v1.x to v2.x in
commit 052b15648f758fe1d7835342d66404ee92ae2426.  The config format
for v2.x has keys and values flipped.

Update lint-staged config to v2.x format.

---

internals/scripts/setup.js

Windows' cmd and powershell do not support `rm` command, hopefully this part of the script now works in all of three major OS's. One question—`dir` argument is unused in `cleanRepo` and `initGit`, should I use it in `path.join` or delete it a altogether?

fix(internal): make `rm -rf .git` work in Windows console

---

internals/webpack/webpack.test.babel.js

Right now if there is a component that imports an svg:
```
import React from 'react';
import Logo from './images/foo.svg';
export default function Header() {
return (
<section>
<h1 className="foo">Foo</h1>
</section>
);
}
```
And we want to create a test: 
```
describe('<Header />', () => {
it('renders `h1`', () => {
const wrapper = shallow(<Header />);
expect(wrapper.find('.foo')).toExist();
});
});
```
The test runner would fail on importing the svg file because the code doesn't support `.svg` extensions via `null-loader` inside the `webpack.test.js` file. Adding it to the `null-loader` solves the issue.

Adding support for svgs during testing

---

.github/CONTRIBUTING.md

After merging this **I'll add a branch called `dev` that all future PRs should be merged into from now on.** (except hot fixes)
This allows us to test changes before releasing them to the wild and avoids massive PRs (like the i18n one) since they can be split into multiple smaller ones.
I think this will greatly help us maintain this boilerplate, but if you have any concerns please let me know in here before we get started!
*Since we're now able to [change the base branch of a PR](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) it's not even that important that people submit it against the correct branch - we can adjust that!*
/cc @gihrig @justingreenberg @oliverturner @SilentCicero @jwinn @chaintan17

Add dev branch

---

.travis.yml

Remove travis sudo (use chromium) and cache node_modules

---

docs/general/deployment.md

This PR adds a step to the deploy docs that instructs you to use heroku's `heroku-postbuild` script tag to run `npm run build` in order to build the static assets on the server. Without this step, you have to build the static files locally and track those generated files (BAD!).

Issue #914: Tweak to deploy docs to include a heroku postbuild of static files.

---

app/containers/App/reducer.js

`fromJS` will convert deep structures (object to Map, array to List). Since we already have one `fromJS` call - we need no second call

remove unnecessary `fromJS` call

---

internals/webpack/webpack.base.babel.js
internals/webpack/webpack.prod.babel.js
internals/webpack/webpack.test.babel.js
package.json

> fixes https://github.com/mxstbr/react-boilerplate/issues/1027
- ~~renamed webpack._.babel.js to webapack._.js as the .babel postfix doesn't work in webpack 2 and it doesnt seem to be used in this project anyway.~~
- ~~removed the sourcemap query from dev as webpack 2 automatically passes through to plugins when set as source-map in the dev-tool option~~
- removed prod jsUglify as this is automatically done with `-p` arg
- moved postCSS config to LoaderOptionsPlugin within webpack

Webpack 2.1.0-beta.25

---

app/components/Button/buttonStyles.js
app/components/Footer/index.js
app/components/Footer/tests/index.test.js

- fixes a vertical alignment issue in the footer
- moves the 4em margin from the bottom to the footer margin-top
- removes unnecessary CSS
Before: 
After:

Fix/simplify footer CSS

---

app/components/Header/HeaderLink.js
app/components/Header/NavBar.js
app/components/Header/index.js
app/components/Header/messages.js
app/components/Header/tests/index.test.js
app/containers/FeaturePage/index.js
app/containers/FeaturePage/messages.js
app/containers/FeaturePage/tests/index.test.js
app/containers/HomePage/index.js
app/containers/HomePage/messages.js
app/containers/HomePage/tests/index.test.js
app/containers/NotFoundPage/index.js
app/containers/NotFoundPage/messages.js
app/containers/NotFoundPage/tests/index.test.js
app/translations/de.json
app/translations/en.json

- simplifies code with `Link` instead of `dispatch(push(...))`
- moves navigation buttons to header to be accessible from all pages and reduce code repetition
- highlights nav buttons when their target matches current browser location, to make more clear what current page is
- makes it easier for projects to then quickly customise navigation
Tested redux + react-router integration still works as expected using Redux DevTools, can replay navigation changes.

Header nav

---

app/containers/FeaturePage/index.js

companion to #811
the `FeaturePage` component class slipped through the cracks of #811, since it used to be a functional component when the pull was first opened... but when i thought about it, this page doesn't really fit the bill for `PureComponent` either. it doesn't need any external props or state to render itself. this is idiomatic use case for `shouldComponentUpdate`—the component only needs to render 1x. the demo is a cool way to expose these simple patterns which might not be obvious to someone new to react... for example, they might ask themselves why using this optimization on a parent component doesn't break it's descendants. in this case, why do the `react-intl` child components still update (ie when toggling locale)? 📚

Add shouldComponentUpdate to FeaturePage (demo)

---

app/store.js
internals/templates/store.js

Added Env variables check to DevTools code based on the new API
Sorry for [#1055](https://github.com/mxstbr/react-boilerplate/pull/1005)

Remove DevTools from Production

---

docs/README.md
docs/general/components.md
internals/webpack/webpack.dev.babel.js

This addresses the issues I've pointed out #955  and attempts to fix them. It also adds some documentation of how to go about extracting components into their own packages (this is one of the most compelling arguments for self contained component architecture).
This is more of a "best effort" attempt, but it has worked well enough for me so far. I am not very familiar with webpack so there's probably a better way, but this solution does make development a lot simpler.

feat(docs) Extracting packages into their own modules

---

internals/scripts/clean.js
internals/templates/constants.js

-Added a constants.js file to templates with the DEFAULT_LOCALE export
-Added a line in clean.js to copy the templates/constants.js file to containers/App/
This resolves the issue of npm run clean breaking because of constants.js not being found since it was being deleted on npm run clean.

Fix 'npm run clean' breaking (#1185)

---

app/components/Toggle/index.js
app/containers/LocaleToggle/index.js

Added a value prop to the Toggle component, being passed down to the Select component to explicitly state which option is selected. The problem seemed to be that when selecting a new language, the component would re-render the options in the order they are passed down via the values prop, thus causing the error.

Fix i18n button not updating (#1181)

---

app/components/Toggle/tests/index.test.js
app/components/ToggleOption/tests/index.test.js
app/containers/LocaleToggle/messages.js
app/containers/LocaleToggle/tests/messages.test.js
app/translations/de.json
app/translations/en.json

This is a fix for Issues #1196, which throws "[React Intl] Missing message" errors to the console when changing language with the locale toggle in the application footer.
*Note: while this fixes this specific problem, there are outstanding still issues when generating new languages with the command `npm run generate language`  (see #1191) .*

Fix console error on lang change

---

.travis.yml
appveyor.yml
docs/general/faq.md
internals/generators/component/index.js
internals/scripts/setup.js
package.json

If using Node v5 or older and you followed the steps listed in **issue #1189**, it would fail on both macOS and Windows.
According to [Node Green](http://node.green/#let), Node v5 should support the use of `let`, but it appears that this is not true given the error. To resolve this I've added `use strict` to the top of `internals/generators/component/index.js`.
As this boilerplate supports the last three major versions of Node.js, see [FAQs](https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md#im-using-node-v012-and-the-server-doesnt-work), this change also includes doc updates along with an improved `setup.js` that will exit on old versions of Node.

Node version support update

---

docs/general/commands.md

The docs are a little confusing on how to get a prod server started. `start:prod` has a undeclared dependency on `build`. So instead, switching the docs to reference the more independent `start:production` cmd is easier for people to follow.

Replace start:prod with independent start:production

---

internals/templates/app.js

When we remove example app, default language is English, not German.

Fix default Intl polyfill language

---

app/containers/RepoListItem/index.js

Currently the example app in the dev branch shows an error message when you try to fetch information:
`git bisect` pointed me to the Jest integration commit and there I noticed this change: https://github.com/mxstbr/react-boilerplate/commit/98f2d0d931ad0945961b66047b47f519734c9db2#diff-f66d28b72b146f6d22bdc2e7aab68001L57 that broke `RepoListItem` component; unless I'm missing something, it's better to replace `createSelector` with `createStructuredSelector` to fix this error.

fix(example): Use `createStructuredSelector` instead of `createSelector` in `RepoListItem`

---

.lgtm
MAINTAINERS

@mxstbr, first it didn't work for a non default branch like you said on gitter, then I did nothing and it started to work ✨, you can see that in my experimental repository: https://github.com/Dattaya/Temp/pull/3
Also, LGTM hook appeared on branch's settings page (appeared unchecked I checked it myself):
#1209

chore(setup): integrate LGTM

---

package.json

Globally disable the ESLint rule (no-confusing-arrow) as per discussion in #1237

Disable ESLint rule: no-confusing-arrow

---

docs/README.md

Fix links in the README of the documentation referring to the styled-components features.

Fix links to styled-components doc

---

app/utils/asyncInjectors.js
internals/templates/asyncInjectors.js

Resolves #1309 by only requiring the lodash pieces in use, the overall file size required is reduced

---

package.json

chore(test config): expand Jest moduleNameMapper key to include common file types.
Resolves #1292

chore(test config): expand Jest config to include common file types

---

internals/templates/languageProvider/languageProvider.js

Fixes regression introduced in #1205, #1320 can be closed once we merge this one.

fix(templates): use correct name of a selector

---

internals/generators/container/sagas.js.hbs

There may well be a better solution, but this eliminates the immediate problem.
Resolves #1231
Open to suggestions.

fix(generator):  'generate container' produces unnecessary return

---

internals/generators/route/routeWithReducer.hbs

`npm run generate route`, for a container with a reducer, for example a `HomePage` component, expected result:
```js
}, {
path: '/test',
name: 'homePage',
getComponent(nextState, cb) {
const importModules = Promise.all([
System.import('containers/HomePage/reducer'),
System.import('containers/HomePage/sagas'),
System.import('containers/HomePage'),
]);
const renderRoute = loadModule(cb);
importModules.then(([reducer, sagas, component]) => {
injectReducer('homePage', reducer.default);
injectSagas(sagas.default);
renderRoute(component);
});
importModules.catch(errorLoading);
},
}, {
```
current result:
```js
},{
path: '/test',
name: 'homePage',
getComponent(nextState, cb) {
const importModules = Promise.all([
System.import('containers/HomePage/reducer'), …
```

chore(internals): fix indentation in 'routeWithReducer'

---

internals/generators/container/sagas.js.hbs

Replaces the solution merged with #1327
A better solution. Handles the problem and guides the user (dev). See updated discussion in #1231

fix(generator): 'generate container' produces unnecessary return - better solution

---

.travis.yml
appveyor.yml
internals/generators/index.js
internals/generators/route/index.js
internals/generators/utils/componentExists.js
internals/scripts/generate-templates-for-linting.js
internals/scripts/helpers/xmark.js
package.json
yarn.lock

Depends on:
TODO
What do you folks think about it, do we need to lint and check for errors of the generators themselves and generated code?

feat(ci): allow for linting of the templates

---

docs/css/README.md

Fix the spelling of `styled-components` in CSS README. There was a PR #1307 open but it was againts `master` and I messed it up 😳 . Thank you for finding this @comerc

Fix spelling in css readme

---

app/containers/HomePage/tests/sagas.test.js
internals/generators/component/es6.js.hbs
internals/generators/component/es6.pure.js.hbs
internals/generators/component/stateless.js.hbs
internals/generators/container/index.js.hbs
internals/generators/container/sagas.test.js.hbs
internals/templates/app.js
internals/templates/global-styles.js

Implements recommendations from #1286 
The updates are slightly opinionated by including propTypes and styled-components. 
I considered replacing the <div> wrapping generated components with a ```styled.div``` Wrapper component, but was unsure if others would find it useful or annoying in the case they don't use them.

fix(generators, templates): add example app functionality into project templates and generators

---

package.json

Use v2 of `image-webpack-loader` as v3 requires environmental dependencies on mac, see #1335 
I'm not sure if we keep note of which dependencies are pinned anywhere? Should we create a doc for this?

Rollback image-webpack-loader

---

internals/scripts/extract-intl.js

Fix for https://github.com/mxstbr/react-boilerplate/issues/1354
-  Currently running `npm run extract-intl` works unless:
User doesn't use other `babel-plugins`, specially transform-plugins such as 
`transform-object-rest-spread`.
- The code repetitively reads `presets` information from `package.json`

Make `extract-intl` compatible with other babel plugins

---

server/index.js

Node's http.Server#listen does some smart choosing for default host '::' or '0.0.0.0' depending on IPv6 support. Use that instead of binding to localhost specifically. This mimics previous server functionality and allows ngrok access to work again.
This fixes #1398

Use node servers default host when none specified

---

.travis.yml
app/app.js
app/routes.js
app/store.js
docs/general/faq.md
docs/general/introduction.md
docs/js/redux-saga.md
docs/js/routing.md
internals/generators/language/polyfill-intl-locale.hbs
internals/generators/route/route.hbs
internals/generators/route/routeWithReducer.hbs
internals/templates/app.js
internals/templates/routes.js
internals/templates/store.js
internals/webpack/webpack.base.babel.js
internals/webpack/webpack.dev.babel.js
internals/webpack/webpack.dll.babel.js
package.json
yarn.lock

Fixes #1346
```js
ERROR in multi main
Module not found: Error: Can't resolve 'babel' in 'F:\react-boilerplate'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
You need to specify 'babel-loader' instead of 'babel'.
```
```bash
22:17  error  Unable to resolve path to module 'containers/App'                                  import/no-unresolved
22:17  error  Missing file extension for "containers/App"                                        import/extensions
25:41  error  Unable to resolve path to module 'containers/App/selectors'                        import/no-unresolved
25:41  error  Missing file extension for "containers/App/selectors"                              import/extensions
28:30  error  Unable to resolve path to module …
```

chore(deps): update webpack

---

docs/general/introduction.md
internals/testing/test-bundler.js
package.json
yarn.lock

__________
We no longer use `chai` assertions. If you guys think that `chai-enzyme` functionality is going to be useful, I can add `jest-enzyme` instead.
I've deleted a link to chai docs from `Introduction`, the testing section of the docs is mostly outdated, …

chore(deps): remove chai and chai-enzyme

---

.travis.yml

Minor edits to `.travis.yaml` as suggested [here](https://github.com/mxstbr/react-boilerplate/pull/1432#issuecomment-272398963).
Should have no effect on operation.

config(travis.yaml): move test and build to script section

---

docs/css/sass.md

New webpack version no longer allowed to omit the '-loader' suffix when using loaders.

Docs Update: sass.md | New webpack version -loader suffix

---

internals/webpack/webpack.base.babel.js

This little fix protects newcomers from going into webpack hell if they include `.otf` fonts. The format is similar to `.ttf`: http://superuser.com/questions/96390/difference-between-otf-open-type-or-ttf-true-type-font-formats

Support OpenType fonts with .otf file extension

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE.md
README.md
app/components/ReposList/tests/index.test.js
app/containers/RepoListItem/tests/index.test.js
docs/README.md
docs/general/faq.md
docs/general/introduction.md
package.json

I have moved `react-boilerplate` to an organisation on GitHub, and added all the maintainers as admins of the organisation. This means I'm no longer the bottleneck for settings, adding team members or releasing—I'm just one of the maintainers.
`react-boilerplate` hasn't been _my_ project for a while. It's maintained by an amazing group of people that make it possible to have one of the most high quality React starter kits without dying under the mass of people using it.
With this change I'm officially recognising this and formally stepping down as "BDFL" (benevolent dictator for life) of react-boilerplate. It's a community project, and I'm just one of a group of rad maintainers. I'm incredibly proud to be a part of this amazing team: @oliverturner, @justingreenberg, @gihrig, @sedubois, …

Move to an org on GitHub

---

package.json

Fixes coveralls reporting?
Discussion in #1535 
#1432 is implicated in the recent failure of Coveralls reporting.
#1432 sought to separate `test` and `build` scripts, but erroneously left `test:clean` in `build:clean`. 
The effect being that 
- `test` built  `./coverage`
- `build` removed `./coverage`
- `coveralls` failed for lack of `./coverage` 
This PR fixxes that error.

test(build:clean script): remove test:clean from build:clean

---

README.md

The current "team of developers" link in the README file is only accessible to authorized users, as reported in #1564.
This PR changes the URL so it is publically accessible. Please note that this link will ONLY show members that have publicized their organization membership. It seems the default is Private, but you can this via the instructions in the link below (I just changed mine).
https://help.github.com/articles/publicizing-or-hiding-organization-membership/

Fix team of developers link in README

---

app/components/List/tests/index.test.js

enzyme API document state that
to use `find()` in ReactWrapper,
the component must be rendered using `mount()` not `render()`
https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/find.md
https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md
reference https://github.com/mxstbr/react-boilerplate/issues/1119

Improve <List> tests

---

docs/js/routing.md

This is literally just pointing broken documentation to the the docs that are pointed to in the react-router repo.

Fix broken link in documentation. Fixes #1638.

---

docs/README.md

PR #1442 added AWS documentation but didn't update the Readme text.

Docs Readme: Fix missing reference

---

app/components/ProgressBar/index.js

This PR removes the `setState()` in `componentWillUpdate` of the ProgressBar component.
See React.Component [componentwillupdate](https://facebook.github.io/react/docs/react-component.html#componentwillupdate) documentation.

Remove state update in componentWillUpdate

---

app/utils/request.js
app/utils/tests/request.test.js

As mentionned in [this issue](https://github.com/react-boilerplate/react-boilerplate/issues/1774), the `request` utils fails when it receive a 204 or 205 HTTP response, as it is trying to parse an empty string (the body) into JSON.
This pull request allows `request` to handle those response by returning a `null`.

Request utils: handle 204 and 205 HTTP response

---

app/components/Header/A.js
app/containers/HomePage/CenteredSection.js
app/containers/RepoListItem/IssueLink.js
app/containers/RepoListItem/RepoLink.js
package.json
yarn.lock

updates project to use to styled-components v2 🎉 
i'm thinking we should probably update deps and cut a release soon...
edit: congrats on the release @mxstbr!! https://www.styled-components.com/

feat(core): styled-components v2 update

---

docs/general/README.md
internals/scripts/extract-intl.js
package.json
yarn.lock

replacing deprecated babel-preset-latest with babel-preset-env
to avoid the following npm installation warning:
```
npm WARN deprecated babel-preset-latest@6.24.0:
preset-latest accomplishes the same task as babel-preset-env.
Please install it with 'npm install babel-preset-env --save-dev'.
'{ "presets": ["latest"] }' to '{ "presets": ["env"] }'.
For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env
```
Ref. #1667

Switching deprecated babel-preset-latest to babel-preset-env

---

app/components/Button/index.js
app/components/Img/index.js
app/components/IssueIcon/index.js
app/components/List/index.js
app/components/ListItem/index.js
app/components/LoadingIndicator/Circle.js
app/components/ProgressBar/ProgressBar.js
app/components/ProgressBar/index.js
app/components/ReposList/index.js
app/components/Toggle/index.js
app/components/ToggleOption/index.js
app/containers/App/index.js
app/containers/HomePage/index.js
app/containers/LanguageProvider/index.js
app/containers/LocaleToggle/index.js
app/containers/RepoListItem/index.js
internals/generators/container/class.js.hbs
internals/generators/container/index.js.hbs
internals/generators/container/stateless.js.hbs
internals/templates/containers/App/index.js
internals/templates/containers/LanguageProvider/index.js
package.json
yarn.lock

`React.PropType` will be deprecated in future releases in favor of `prop-types` package.
From React's website:
> Prop types are a feature for runtime validation of props during development. We've extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them.
> 
> In 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there
More info at [this link](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes)

Migrating from React.PropTypes to PropTypes

---

docs/README.md

The link to "tagged template literals" redirects the user to styled-components.com. This PR updates the link to go directly to styled-components.com. …

Update the "tagged template literals" link to point to its new home

---

app/app.js
app/store.js
app/tests/store.test.js
docs/README.md
docs/general/introduction.md
internals/templates/app.js
internals/templates/store.js
internals/webpack/webpack.dev.babel.js
package.json
yarn.lock

This is an alternative to https://github.com/react-boilerplate/react-boilerplate/pull/1207.
Downsides:
- does not preserve component's state but Redux state will be in place;
- could be annoying to some devs that injected non-daemon sagas will be restarted on each change in components, though in my experience it's not a big deal.
Upsides:
- very simple setup;
- works with any kind of component unlike deprecated `react-hmre`;
- `react-hot-loader` is still fragile with a lot of edge cases, here we have none;
- injected sagas and reducers will be hot re-loadable for free (no additional setup necessary).
/cc @justingreenberg, @marnusw, @anuraaga
[justingreenberg] edit: resolves #1068

Replace `preset-hmre` with vanilla webpack HMR

---

internals/generators/container/class.js.hbs

Currently, the reducer key does not match the key generated for the selector, so generated containers don't work. This PR makes the reducer key match, and updates the saga key as well for consistency.
Be kind to code reviewers, please try to keep …

Use camelcase for generated reducer and saga key to match selector.

---

package.json
yarn.lock

`sanitize.css` adds `background: transparent` to inputs thus making them loose their native styling (as was pointed out by @vicbell) for no good reason, [the fix was merged](https://github.com/jonathantneal/sanitize.css/pull/137) but not yet released so for the time being I propose to downgrade `sanitize.css` to 4.1.0.

chore(deps): downgrade `sanitize.css`

---

internals/templates/containers/App/index.js

Fixes #1884
Turned `App` into a functional component to be consistent with `App` in the example application also I don't think extending it from `PureComponent` provides any benefits over a regular component or function in this case.

chore(templates): turn `App` into a functional component

---

yarn.lock

`yarn.lock` was not regenerated in #1832 as I asked, so I'm doing it here, it would be nice to merge it before releasing 3.5 (#1929).

chore(deps): regenerate `yarn.lock`

---

internals/webpack/webpack.base.babel.js

This PR fixes the following warning which come as a result of using images in the components:
```
./app/assets/images/image.png
(Emitted value instead of an instance of Error) DEPRECATED. Configure gifsicle's interlaced option in its own options. (gifsicle.interlaced)
@ ./app/containers/HomePage/index.js 24:0-75
@ ./app/containers/HomePage/Loadable.js
@ ./app/containers/App/index.js
@ ./app/app.js
@ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```
The solution was found in this SO thread: https://stackoverflow.com/questions/42206190/webpack-2-warning-in-png-svg-deprecated-configure-optipngs-optimizatio.

fix(internals): Update `image-webpack-loader` query

---

app/index.html

Add `<meta name=“referrer” content=“origin”>` to make the application more secure by not sending the full url to servers other than the origin.

feat(core): Set Referrer Policy to "origin" using document meta tag

---

app/index.html

Use the right quotes for the referrer policy.
Sorry for this very weird fault.

fix: quotes in referrer policy

---

app/components/Button/index.js

*In: app/components/Button/index.js*
Prop **route** was changed to **handleRoute** in Jan 19, 2016, but the commented instructions were not updated.

fix(docs): Update `route` prop description for Button component

---

app/manifest.json
docs/general/gotchas.md

Addresses #1985 by adding a `short_name` field to the app manifest. 
When there's insufficient space to display an app's full name, it gets truncated. This happens with app launcher and new tab in Chrome for Android. The `short_name` field allows a 12 character or less abbreviation. It also addresses any problems in testing the PWA in Lighthouse.

feat(core): Add short_name to manifest.json

---

docs/js/immutablejs.md

These need to be wrapped to avoid this anti-pattern: http://redux.js.org/docs/recipes/UsingImmutableJS.html#make-your-entire-redux-state-tree-an-immutablejs-object

Wrap setters in fromJS inside reducer

---

app/.nginx.conf

With the addition of the 'Do not cache sw.js' block, the root path, that is in the 'Always serve index.html' block, should move to the main server block or the sw.js will not be found.

fix(.nginx.conf) moving root path to the main server block

---

internals/webpack/webpack.base.babel.js

With this PR, webpack will inline small images (smaller than 10,000 bytes) instead of emitting them as separate files. This would save an extra request (pretty important for HTTP/1 and might have a small effect for HTTP/2).
The `url-loader` is also already enabled for video files: https://github.com/react-boilerplate/react-boilerplate/blob/e39f8bdca29a35edbd7480968c9fe0b2c9438860/internals/webpack/webpack.base.babel.js#L74-L82

Use the url-loader to inline small images

---

app/utils/sagaInjectors.js
app/utils/tests/sagaInjectors.test.js

When the saga ejector tries to eject a done saga, it attempts to cancel a non-existent related task for that saga. This fixes the conditional to prevent entry into any ejection code for a done saga. It also fixes a test to work with this change, as there is no such thing as a default mode saga.
Fixes #2021

Fix ejection error of done sagas

---

internals/scripts/extract-intl.js

One method in file uses wrong declaration for one variable. 
f.e. uses next way:
```
try {
const localeTaskDone = () => (error) => {}
localeTaskDone();
}
catch(e ){
localeTaskDone(e);
}
```
It's quite evident that `localeTaskDone` is not available in catch block, because it is declared in try block.

fix(internals): Fix extract-intl incorrect variable declaring

---

docs/js/redux.md

Multiple reducers can not be applied to store key
Closes PR #2061 as duplicate
Updated dev branch as asked by @gretzky

Update redux reducer doc noting unique key

---

app/components/Header/tests/A.test.js
app/components/Header/tests/Img.test.js
app/components/LoadingIndicator/tests/index.test.js
app/containers/RepoListItem/tests/IssueIcon.test.js
app/containers/RepoListItem/tests/IssueLink.test.js
app/containers/RepoListItem/tests/RepoLink.test.js
internals/testing/enzyme-setup.js
package.json

Upgrade to Enzyme 3
This resolves what I believe to be the major blocker for React 16
Resolves #1950

chore(internals): Upgrade enzyme to v3

---

app/containers/HomePage/actions.js

Small fix for jsdoc type of `name`, which should be type `string` instead of type `name`

Fix name parameter jsdoc type

---

docs/README.md

This fixes #1741. For me at least, this worked to get through the quickstart (changing the `messages.features` inside `message.js` didn't work).
Regarding linting, I don't know how the markdown needs to be wrapped, but this made sense for me.

Fix quickstart instruction for showing HMR in action

---

.travis.yml
appveyor.yml
docs/general/faq.md
internals/scripts/extract-intl.js
package.json
yarn.lock

Add `babel-plugin-transform-react-jsx-source` to `dev`, which has been done by @justingreenberg but not in `dev`, see comment [here](https://github.com/react-boilerplate/react-boilerplate/pull/1969#issuecomment-339693446). [Here](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html#component-stack-traces) is why we need this plugin.

 feat(core): Add babel-plugin-transform-react-jsx-source

---

internals/scripts/clean.js

When I opened clean.js file I saw some eslint errors for semicolons. It seems clean.js is ignored from eslint check (--ignore-pattern internals/scripts)

add missing semicolon in clean.js which is ignored file for eslint checks

---

internals/generators/component/class.js.hbs
internals/generators/component/stateless.js.hbs

Currently using the component  generators creates the propTypes object on a component, but **does not** import PropTypes resulting in  ```Uncaught ReferenceError: PropTypes is not defined``` if you forget to add the import. Seems like if the generator does one it should also do the other.
I added ```//import PropTypes from 'prop-types';``` to the class and stateless component generators as a fix, commented out so it doesn't blow up es-lint with `'PropTypes' is defined but never used  no-unused-vars` errors

Import prop types in component class and stateless generators

---

docs/css/README.md

The [previous link](https://github.com/styled-components/styled-components/blob/master/docs/css-we-support.md) took you to a page asking to update bookmarks, so I've changed the link to the new one.
Hope it's okay to clear out the PR template since this is so small.

docs: Fixed styled-components Supported CSS link

---

package.json

Closes #2111 
This adds `--fix` flag in the `lint:eslint` script in `package.json`. Allows to try to run eslint fixers before showing line errors to users.

Adds eslint --fix flag ( to auto-apply eslint fixers )

---

app/utils/injectSaga.js
app/utils/sagaInjectors.js
app/utils/tests/injectSaga.test.js
app/utils/tests/sagaInjectors.test.js
internals/templates/utils/injectSaga.js
internals/templates/utils/sagaInjectors.js
internals/templates/utils/tests/injectSaga.test.js
internals/templates/utils/tests/sagaInjectors.test.js

This PR needs some additional tests, but I wanted to have your feedback first.
In RBP 3.4 you would create your sagas as
```js
function* mySaga(action) {
console.log(action); // { type: 'MY_ACTION' }
}
```
In 3.5 instead if you're using the `injectSaga` you end up with
```js
function* mySaga(whatsThis) {
console.log(whatsThis); // it's the whole props object
// turns out that the action is now the second parameter
}
```
As I'm updating my code, I really don't fancy modifying all my sagas to add an extra argument.
Moreover, I don't really like using props inside my saga, feels brittle. I thought the whole point of using actions was to pass parameters to a saga that doesn't have to depend on the props.
Finally, in another project based on 3.4 I need to access a firebase instance …

Allow to pass additional parameters to the injected sagas

---

docs/general/README.md
docs/general/editor.md

Follow up on #2073
Adds a new docs page about setting up your editor. This page specifically documents creating a `jsconfig.json` to improve the editing experinace with VS Code, which was the focus of #2073

Add "Setting  up your editor" docs section

---

README.md

we keep getting several messages about updating certain dependencies-- ie react 16, webpack 4, etc. we're aware of them, and many people have opened PRs with their updated forks. 
i go on a rant about this [here](https://github.com/react-boilerplate/react-boilerplate/issues/2200#issuecomment-385966234)
i think it's necessary to dump a message into the README asap just so we can direct any new issues to that and close them immediately

update readme to add brief announcement on releases/updates

---

internals/webpack/webpack.base.babel.js

As encountered [here](https://github.com/ReactTraining/react-router/issues/6126), if someone uses and extends the boilerplate to create a singleton of say, `history` so it can be used in sagas/epics and so on, the module resolution order of apps -> node_modules means that react-router components like Redirect will import from the wrong instance of `history` (the local declaration in /app instead of the actual library in /node_modules).
Switching the order doesn't seem to cause any harm and means less chance of this affecting users.
Also splitting up the fields in the array onto multiple lines since it fits with all the other nearby arrays 😄 
Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/bl …

Updating order of module resolution in Webpack config

---

.github/lock.yml

I've added [Lock](https://probot.github.io/apps/lock/), a bot that locks closed issues that are a certain age old. I've set the number of days to be 30, because I constantly get notifications of people who are commenting on closed issues. Most of these comments / issues aren't an rbp-related issue, rather just asking for help. I want to curb convos on old, closed issues and then if/when someone opens a new issue, we can either solve the problem or direct them to StackOverflow. 
Let me know if this is overkill, but I think it just takes some of the weight off.

add Lock app template

---

internals/scripts/clean.js
internals/scripts/generate-templates-for-linting.js

Reverts react-boilerplate/react-boilerplate#2229 @ochanje210 
Needs to fill out the PR template and change base branch to `dev` to maintain best practices.

Revert "Fix few eslint errors"

---

.eslintrc.js

The `path` argument of `fs.readFileSync` is relative to the working directory, so linting in Atom was broken for mono-repos (as eslint is not executed from the project root).

Use .prettierrc path relative to .eslintrc.js

---

app/components/Footer/messages.js
app/components/Header/messages.js
app/containers/FeaturePage/messages.js
app/containers/HomePage/messages.js
app/containers/LocaleToggle/messages.js
app/containers/NotFoundPage/messages.js
docs/js/i18n.md
internals/generators/component/messages.js.hbs
internals/generators/container/messages.js.hbs
internals/templates/containers/HomePage/messages.js
internals/templates/containers/NotFoundPage/messages.js

Fixes #2361 
- readds the changes from #1799
- adds export directives for the message scopes for use in other files (e.g. `import messages, { scope } from '..../messages';`) 
- updates the docs at [/docs/js/i18n.md](https://github.com/react-boilerplate/react-boilerplate/pull/2367/files?short_path=43cd55f#diff-43cd55f1b45606ea69d2083d139cd5cc)

feat(i18n): Readded: Use namespaced variables in message paths

---

app/index.html
app/utils/checkStore.js
app/utils/reducerInjectors.js
app/utils/sagaInjectors.js
app/utils/tests/injectReducer.test.js
app/utils/tests/reducerInjectors.test.js
babel.config.js
internals/scripts/dependencies.js
internals/templates/index.html
internals/templates/utils/checkStore.js
internals/templates/utils/reducerInjectors.js
internals/templates/utils/sagaInjectors.js
internals/templates/utils/tests/injectReducer.test.js
internals/templates/utils/tests/reducerInjectors.test.js
package-lock.json
package.json

Two small changes:
First, a fight to the death between `path.join` and `path.resolve` (per #2378). I think `path.join` wins. Unless it creates another issue I didn't think of?
Second, I added lodash's official [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to production plugins in Babel. It replaces `import { get } from 'lodash';` with `import get from 'lodash/get';`. I know we already use the latter by default but in case a user forgets to do the same, it saves them from adding an additional 70k to their bundle.

Path fix and lodash babel dev

---

app/containers/App/tests/reducer.test.js
app/containers/App/tests/selectors.test.js
app/containers/HomePage/tests/reducer.test.js
app/containers/HomePage/tests/selectors.test.js
app/containers/LanguageProvider/tests/reducer.test.js
app/containers/LanguageProvider/tests/selectors.test.js
app/utils/tests/reducerInjectors.test.js
internals/generators/container/reducer.js.hbs
internals/generators/container/reducer.test.js.hbs
internals/generators/container/selectors.js.hbs
internals/generators/container/selectors.test.js.hbs
internals/templates/app.js
internals/templates/configureStore.js
internals/templates/containers/App/selectors.js
internals/templates/containers/App/tests/selectors.test.js
internals/templates/containers/LanguageProvider/reducer.js
internals/templates/reducers.js
internals/templates/utils/tests/reducerInjectors.test.js

Apologies for the duplicate pull request, I wanted to fix the botched history.
Not to step on anyone's toes, but I love this boilerplate and I definitely want to use it with immer on my next project. I saw this branch and I wanted to see how it would look as far as testing goes, as well as having it implemented in any components we scaffold with reducers, so I went ahead and replaced the rest of the instances of ImmutableJS within the code. I haven't touched documentation, but I thought it might save you the bit of time it takes to refactor, should you all decide to go this route.
All Jest tests are passing.

replaced immutablejs with immer in tests and internals

---

internals/generators/container/saga.js.hbs
internals/generators/container/saga.test.js.hbs

Hello guys,
Firstly, I think it will be better if generated saga file has a meaning name rather than `defaultSaga` in case of debugging.
Lastly, since `saga.js` file had a default export, so there is no reason why in `saga.test.js` file, it is imported as a single export.
Thanks for your good work.
Please let me know if I can update anything.

camelCase name for saga

---

internals/webpack/webpack.base.babel.js
internals/webpack/webpack.prod.babel.js
package-lock.json
package.json

I've been incorporating some changes from the dev branch into a project I built with the previous release, and I ran into this issue at build time: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/359
Turns out uglifyjs-webpack-plugin is no longer using uglify-es on the backend as it's no longer actively maintained, and they recommend switching to terser. There may be a good reason to stay on Uglify, I honestly haven't dug in too deeply, but this configuration is working on my project and it might save people from some small headaches in the future.

switched to terser-webpack-plugin from uglifyjs-webpack-plugin

---

.github/issue-close-app.yml

Pushing to master because it doesn't have to do with actual development.
This adds the config file needed for close-issue-app, it looks for the headers of the issue template.
**edit** whyyy did it pull in 3 commits -_-. rebased w/ master, it should be ok now

Add close-issue-app to probot

---

CONTRIBUTING.md

Fix link to maintainers in contributing.md

---

app/utils/injectReducer.js
app/utils/injectSaga.js
internals/templates/utils/injectReducer.js
internals/templates/utils/injectSaga.js

This is an alternative to @tonyex52's fix for #2314 in his PR #2467.
Instead of making injection Promise-based (which has a few drawbacks not addressed in #2467), we simply do the injection from the constructor.
It'll guarantee that things happen in the correct order, as described by @flameddd in #2314.
All tests are passing with no changes required.
I also did the same thing for reducer injection, if only for consistency.
Also, a small doc update that was missed when we switched the default saga injection mode to DAEMON.

Use constructor instead of cWillMount for correct injection order

---

.github/issue-close-app.yml

I've seen a few people post issues without using the template who are then confused to see them locked (cf. #2471). I updated the lock bot message to hopefully remove a little bit of confusion.

Add details to lock bot message

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/issue-close-app.yml

I think these changes would allow us to turn the issue close bot back on. Do you agree?
(I removed the mention of package.json because I'm assuming most users overwrite the version when starting to build their own apps. In fact, we probably ought to set it to 0.1.0 or something similar in the setup script.)

Update issue template and issue-close-app

---

README.md

Correcting my mistake on pull #2504 .

Link for github org no longer 404

---

app/configureStore.js

Very small tweak to use [redux-saga devtools extension](https://github.com/abettadapur/redux-saga-devtools-extension) if available (chrome only?)

Add support for redux-saga-devtools-extension

---

app/containers/FeaturePage/Loadable.js
app/containers/HomePage/Loadable.js
app/containers/NotFoundPage/Loadable.js
app/utils/loadable.js
docs/js/async-components.md
internals/generators/component/loadable.js.hbs
internals/templates/containers/HomePage/Loadable.js
internals/templates/containers/NotFoundPage/Loadable.js
internals/templates/utils/loadable.js
package-lock.json
package.json

With [React 16.6](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#reactlazy-code-splitting-with-suspense) we can load components asynchronously using `lazy` and `Suspense`. Negligible difference in bundle size but it's still nice to use native React features instead of an additional dependency.
@gretzky @justingreenberg What do you think? Should we implement this? I'll finish the PR if relevant!

Code splitting with Suspense

---

internals/generators/index.js
internals/generators/language/index.js
internals/scripts/generate-templates-for-linting.js

In order to test the generator functionality the `test-generators-without-a-trace` is executed on Travis. This runs all generators for components/containers and language.
Then the linter is scheduled to run so it inlcudes these generated components etc.
But any, snapshot, test for components wrapped in `<LanguageProvider />` fail because of the added language by the language generator.
Therefore I've rewritten the `test-generators-without-a-trace` script. It runs all generators as before but checks for linting issues right after and on the component, container or modified file, if the generation was successful.
When the generator actions were successful and no linting problems were found the component, container or any added files are removed and modified files are restored.
In case any …

Rewritten the generate-templates-for-linting script

---

.eslintrc.js

ESLint's IDE extensions always add two trailing commas per line when writing an object, an array, or a list of arguments, etc. It can be very annoying. This is a quick fix for this issue. The prettier config + its ESLint plugin already take care of trailing commas for us so in this branch I removed the dedicated ESLint rule. The bug goes away when you do that.

Fix for double comma linting issue

---

app/components/Header/index.js
app/components/Header/tests/__snapshots__/index.test.js.snap
app/containers/FeaturePage/index.js
app/containers/FeaturePage/tests/index.test.js
app/containers/HomePage/index.js
app/containers/HomePage/tests/index.test.js
app/containers/LanguageProvider/index.js
app/containers/LocaleToggle/index.js
app/containers/RepoListItem/index.js
app/utils/injectReducer.js
app/utils/injectSaga.js
internals/templates/containers/HomePage/index.js
internals/templates/containers/LanguageProvider/index.js
internals/templates/containers/NotFoundPage/index.js
package-lock.json
package.json

The saga and reducer injectors are normally used via HOCs.
The HOCs will still work with Hooks-based components but IMO, we can offer a nice alternative which doesn't pollute the render tree:
`useInjectSaga` and `useInjectReducer` hooks!
You can see this alternative in this PR's diff [here](https://github.com/react-boilerplate/react-boilerplate/pull/2583/files?w=1) (with the no whitespace option enabled).
We probably shouldn't remove the HOCs as the Hooks-based injectors won't work with Class components.
I do have one question about the InjectSaga HOC: It passes props to `injectSaga`. What's the purpose of this and is there any way around it?
This is more of an RFC than anything else. Looking for thoughts and feedback before completing the branch.
Cheers!
PS: `react-helmet@5` + …

[RFC] Hooks-based saga and reducer injectors

---

package-lock.json
package.json

I couldn't find any release info for `react-redux` `7`, but there doesn't appear to be anything the bp is dependent upon that was deprecated/removed, as it appears `v7` to be a move to using hooks internally.

chore(core): upgrade to react-redux 7

---

internals/webpack/webpack.prod.babel.js

I tested the code-splitting instructions laid out in [this article](https://hackernoon.com/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758). Here are the results of building the sample app before and after (with gzipping turned off for clarity):
Before:
After:
As you can see, the vendor bundle is broken down into several small scripts and the entrypoint size limit warning is gone. (Perhaps because not all the vendor scripts are needed initially?) Especially for users of HTTP2, this seems like an improvement IMO.
@gretzky You wrote the current config so I'd be particularly interested in hearing your thoughts on this.

New Webpack code-splitting config

---

internals/webpack/webpack.base.babel.js

Restored support for .jsx files to fix #2634.

JSX file support

---

internals/webpack/webpack.prod.babel.js

Without this change, the manifest/icons is not cached by the service worker

Generate manifest.json, before the service worker
