.eslintrc
docs/COMMANDS.md
js/components/pages/HomePage.react.js
js/components/pages/ReadmePage.react.js
package.json

- fixed some files having both space and tab indent.
- added lint and test:watch to npm scripts
Closes #23

Indentation fix and scripts update

---

js/actions/.keep
js/components/.keep
js/constants/.keep

fixed some typos.

---

.eslintrc
app/js/components/App.react.js
app/js/components/pages/HomePage.react.js
app/js/components/pages/NotFound.react.js
app/js/components/pages/ReadmePage.react.js
app/serviceworker.js
package.json
webpack/server.dev.js
webpack/server.prod.js
webpack/webpack.dev.config.js
webpack/webpack.prod.config.js

Mostly a clone of https://github.com/mxstbr/react-boilerplate/pull/42, except with additional changes. In addition, it looks like the merge in a48c5a5b5da705bdab49acaf2bba4d6ce68d2001 did not properly merge the `package.json` scripts, so Travis giving green builds with more lint violations get through.

Enforce linting for green builds

---

README.md

Add Babel to README

---

app/app.js
app/containers/HomePage/HomePage.actions.js
app/containers/HomePage/HomePage.react.js
app/containers/HomePage/HomePage.reducer.js
app/containers/ReadmePage/ReadmePage.react.js
package.json
webpack/server.prod.js

@mxstbr 
Mostly this just makes sure lines are < 100 chars, however `Homepage.react.js` had to enforce https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

Upgrade eslint style rules to airbnb-3.0.0

---

package.json

`react-dom` is duplicated on devDependencies

Remove duplicated ReactDOM.

---

package.json
webpack/server.dev.js
webpack/server.prod.js

I encountered some problems with git. So, it's new pull request (lol).
Old request — https://github.com/mxstbr/react-boilerplate/pull/83
Preview:
https://monosnap.com/file/XsJtEYCF6w1kzLCDJAjfo4ElC21KXD
https://monosnap.com/file/GxvvVZrTq4Rx4U5S1iwmDfbfDFou1G

Add new logs and styling #81

---

app/app.js
app/containers/HomePage/index.js
app/containers/NotFoundPage/index.js
app/containers/ReadmePage/index.js
app/rootReducer.js
package.json

Fix #116.
See rackt/react-router-redux#80

Update to react-router-redux

---

README.md
docs/general/commands.md
package.json

Updated the README with proper instructions and updated package.json with proper script name.

'npm run initProject' changed to 'npm run setup'

---

.stylelintrc
app/components/A/styles.css
app/components/Button/styles.css
app/components/Footer/styles.css
app/components/H1/styles.css
app/components/H2/styles.css
app/containers/App/styles.css
app/containers/FeaturePage/styles.css
app/containers/HomePage/styles.css
app/containers/LoginForm/styles.css
package.json

Fix stylelint errors

---

app/app.js
package.json

scroll to top after route transition

---

app/containers/FeaturePage/index.js
app/containers/HomePage/index.js

Change constructor binded functions to es6 autobinding functions

---

.travis.yml

Use "trusty" on Travis for isolated builds

---

internals/webpack/webpack.base.babel.js
internals/webpack/webpack.dev.babel.js
internals/webpack/webpack.prod.babel.js
package.json

This PR should close both #126 and #127.

CSS processing and long-term caching

---

app/app.js
app/store.js

Added Redux Devtools Extension support #207 and fixed small sanitize.css bug.

#207 Adding Redux Devtools Extension and fixing a small bug in sanitize.css

---

README.md

Hope the wording is ok? Could't help myself but to include the typo fixes. I can of course quickly remove them if you don't want them.

Update README, point users to the v3.0.0 branch

---

internals/webpack/webpack.dev.babel.js

Readable localIdentName

---

docs/general/README.md

Links were broken on the Github Read.me preview.

Fix broken links.

---

package.json

Uses rimraf for cross-platform consistency

Fixes #223: `build:clean` task added `prebuild` task

---

docs/general/features.md
docs/testing/component-testing.md
docs/testing/unit-testing.md

Fix broken links in docs

---

app/containers/HomePage/index.js
app/containers/RepoListItem/index.js
app/sagas/getGithubData.saga.js
app/sagas/tests/getGithubData.test.js
app/selectors/currentUserSelector.js
app/selectors/errorSelector.js
app/selectors/globalSelector.js
app/selectors/homeSelector.js
app/selectors/loadingSelector.js
app/selectors/reposSelector.js
app/selectors/routeSelector.js
app/selectors/selectLocationSelector.js
app/selectors/tests/currentUserSelector.test.js
app/selectors/tests/errorSelector.test.js
app/selectors/tests/globalSelector.test.js
app/selectors/tests/homeSelector.test.js
app/selectors/tests/loadingSelector.test.js
app/selectors/tests/reposSelector.test.js
app/selectors/tests/routeSelector.test.js
app/selectors/tests/selectLocationSelector.test.js
app/selectors/tests/usernameSelector.test.js
app/selectors/usernameSelector.js
internals/generators/container/index.js.hbs
internals/generators/container/selector.js.hbs
internals/generators/selector/selector.js.hbs
internals/generators/selector/test.js.hbs

V3.0.0 use wrapper functions for selector creation

---

Changelog.md
docs/css/README.md
docs/css/sass.md
docs/css/stylelint.md

- Added a note on stylelint 
- Made the argument against Sass a bit more coherent
- Moved CHANGELOG.md into the root

Yet moar tweaks

---

docs/js/remove.md

as discussed in https://github.com/mxstbr/react-boilerplate/issues/272#issuecomment-209386771

Describe how to use syncHistoryWithStore without reselect

---

app/containers/App/reducer.js
app/containers/App/tests/reducer.test.js

True should be a keyword, not a variable

---

README.md

- Added CI setup to README features section
- Added keywords to README
- Bolded commands in README

More documentation updates

---

internals/generators/component/es6.js.hbs
internals/generators/route/index.js
internals/generators/route/route.hbs
internals/generators/route/routeWithReducer.hbs

Fix generators

---

internals/scripts/clean.js
internals/templates/routes.js

Atm after running npm run clean boilerplate is broken. This pr fixes it.

Fix run clean script and template

---

internals/scripts/clean.js
internals/templates/routes.js

My first contribution ever! I tested it and the cleaned app show the HomePage on startup.

Apply changes required in order to make the cleaned version works.

---

package.json

Just released it with bunch of updates and fixes.
See changelog here: https://github.com/NekR/offline-plugin/blob/master/CHANGELOG.md

Update offline-plugin to v3

---

package.json

fix chalk dep

---

app/components/Button/index.js
app/components/Img/index.js
app/components/ListItem/index.test.js

Import PropTypes from react like in A component.

Import PropTypes from react

---

app/components/A/tests/index.test.js
app/components/Button/tests/index.test.js
app/components/Footer/tests/index.test.js
app/components/H1/tests/index.test.js
app/components/H2/tests/index.test.js
app/components/H3/tests/index.test.js
app/components/Img/tests/index.test.js
app/components/IssueIcon/tests/index.test.js
app/components/List/tests/index.test.js
app/components/ListItem/tests/index.test.js
app/components/LoadingIndicator/tests/index.test.js
app/containers/FeaturePage/tests/index.test.js
app/containers/HomePage/tests/index.test.js
app/containers/NotFoundPage/tests/index.test.js
app/containers/RepoListItem/tests/index.test.js
app/tests/store.test.js

css lint fails with these errors.
```
> react-boilerplate@3.0.0 lint:css /Users/bsr/tmp/react-boilerplate
> stylelint ./app/**/*.css
app/components/A/styles.css
2:10  ✖  Expected "ADDD" to be "addd"      unit-case      
2:10  ✖  Unexpected unknown unit "ADDD"    unit-no-unknown
6:10  ✖  Expected "CC0E5" to be "cc0e5"    unit-case      
6:10  ✖  Unexpected unknown unit "CC0E5"   unit-no-unknown
app/components/Button/styles.css
24:21  ✖  Expected "ADDD" to be "addd"     unit-case      
24:21  ✖  Unexpected unknown unit "ADDD"   unit-no-unknown
25:10  ✖  Expected "ADDD" to be "addd"     unit-case      
25:10  ✖  Unexpected unknown unit "ADDD"   unit-no-unknown
29:15  ✖  Expected "ADDD" to be "addd"     unit-case      
29:15  ✖  Unexpected unknown unit "ADDD"   unit-no-unknown
```
but, tests …

#317 consistent folder structure for tests

---

app/.nginx.conf

Changes "shure" to "sure" in .nginx.conf file.

Fix typo in comments

---

internals/webpack/webpack.base.babel.js

I had a problem with some packages (same error as [here](https://github.com/webpack/webpack/issues/592)). I got to do this fix to get everything work. Maybe It could help others.

Update base webpack config with Json loader

---

internals/scripts/helpers/progress.js
internals/scripts/setup.js

Switch the setup script to readline for Windows compatability #328

Switch the setup script to readline for Windows compatability #328

---

README.md

Changed method of cloning mentioned in repo

---

docs/css/css-modules.md

Adds able between 'being' and 'to' in first paragraph.

Fix tiny grammar error

---

app/index.html

For some reason there were mixed space/tabs in `index.html`. That should be fixed now.

Changed Tabs to Spaces

---

internals/templates/appContainer.js
internals/templates/homePage.js
internals/templates/notFoundPage.js

Use class components in template files

---

docs/README.md

changed 'npm setup' to 'npm run setup'

Fix the first command in the overview section

---

internals/generators/component/test.js.hbs

wrong path to component to be tested

Fix component test generator

---

app/components/ListItem/index.js
app/components/ListItem/tests/index.test.js
app/containers/HomePage/index.js
app/containers/RepoListItem/index.js

Change ListItem content props for item props

---

internals/testing/karma.conf.js

```
START:
19 05 2016 11:53:20.971:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 05 2016 11:53:20.984:INFO [launcher]: Starting browser Chrome
19 05 2016 11:53:22.416:INFO [Chrome 49.0.2623 (Mac OS X 10.11.3)]: Connected on socket /#rNoswUWdY2L5DopLAAAA with id 7918641
ERROR: 'Warning: Failed propType: Required prop `href` was not specified in `A`.'
<A />
✔ should render its children
ERROR: 'Warning: Failed propType: Required prop `children` was not specified in `A`.'
✔ should adopt the className
✔ should adopt the href
✔ should adopt the target
<Button />
✔ should render its children
ERROR: 'Warning: Failed propType: Required prop `children` was not specified in `Button`.'
✔ should adopt the className
✔ should render an <a> tag if no route is specified
✔ should …
```

log coverage during npm test

---

package.json

.. with couple of [new rules](https://github.com/stylelint/stylelint-config-standard/blob/master/CHANGELOG.md#800) :)

Update stylelint-config-standard to 8.0.0

---

docs/js/remove.md

Changed example code to convert state object to raw js with toJS()

Updated docs for removing reselect

---

internals/webpack/webpack.prod.babel.js

* Remove `relativePaths: true` because it's `true` by default
* Add `safeToUseOptionalCaches: true` to remove warnings about additional caches
* Make AppCache cache both sections: `main` and `additional`
_____________________________________
Copy of https://github.com/mxstbr/react-boilerplate/pull/378 PR from v3 branch

OfflinePlugin fixes and improvments 

---

app/containers/HomePage/sagas.js
app/containers/HomePage/tests/sagas.test.js

Alternative to #390, resolves #384

Fix example saga

---

internals/scripts/setup.js

re install pre-commit after setup

---

app/containers/FeaturePage/index.js
app/containers/HomePage/sagas.js
app/containers/RepoListItem/index.js
app/utils/hooks.js
app/utils/request.js
internals/scripts/analyze.js
internals/scripts/clean.js
internals/scripts/helpers/checkmark.js
internals/scripts/helpers/progress.js
internals/scripts/pagespeed.js
internals/scripts/setup.js
internals/templates/appContainer.js
internals/templates/homePage.js
internals/templates/notFoundPage.js
internals/testing/karma.conf.js
package.json
server/logger.js

Clean up JS linting

---

internals/generators/container/index.js
internals/generators/route/index.js

Remove the magic numbers and the problem is solved.

Fix the generator only works when indentation is 2.

---

internals/generators/index.js
internals/generators/route/index.js
internals/generators/route/route.hbs

Fixes [#484](https://github.com/mxstbr/react-boilerplate/issues/484).

Fix bug: route generator checking for component directory.

---

internals/generators/container/index.js

[#331](https://github.com/mxstbr/react-boilerplate/issues/331) and [former pull request #501](https://github.com/mxstbr/react-boilerplate/pull/501#issuecomment-224637849)

Remove static reducer from generator

---

docs/general/README.md
docs/general/remove.md
internals/webpack/webpack.base.babel.js
package.json

https://github.com/mxstbr/react-boilerplate/issues/510
_My english is not that good, so feel free to improve the documentation if it could be better :)_

Add image optimization to webpack process

---

server/middlewares/frontendMiddleware.js

Fixes #548. Thanks @zanedev
Pushing this in hope that the status checks pass and we can merge.  The previous attempt seems hung

Argument order bug - fixes #548

---

docs/general/commands.md

Updated documentation for setting a custom port

---

internals/webpack/webpack.base.babel.js

See [url-loader README](https://github.com/webpack/url-loader).

let url loader infer mimetype from file extension

---

server/index.js

Fix comment about how to use custom middlewares

---

README.md

Video contains speech "Scaling React.js Applications"  delivered
by Mas Stoiber at oredev conference 2016. It provides insights
about scalable design of React applications which used in
react-boilerplate.

Add link to speech from dev conference to Readme

---

docs/general/deployment.md

The prior documentation did not make the deployment requirements very clear. Updated as per the discussion here: https://github.com/mxstbr/react-boilerplate/issues/561

Updated the Heroku deployment documentation

---

docs/general/faq.md

This is mostly taken from my answers in #526, these questions come up quite often so I figured we should add a section to the FAQ!
/cc @oliverturner who might want to chime in here

(docs) Add non-route container section

---

docs/css/sanitize.md

I changed state because sanitize.css is not PostCSS plugin. Ref #593

Fix: sanitize.md: state

---

package.json

Rollup of all GreenKeeper suggested updates over a six day period ending 07-07-2016 with Update stylelint to version 6.9.0
This rollup was done to facilitate thorough local testing and conflict resolution. When all CI checks pass those GK update branches can be deleted.

Dependency rollup

---

internals/generators/component/es6.js.hbs

Adding the flag for disabling eslint on ES6 classes

ES6 class eslint disabling

---

docs/README.md
docs/general/README.md
docs/general/commands.md
docs/general/faq.md
docs/js/README.md
docs/js/routing.md
docs/testing/README.md
docs/testing/remote-testing.md

I think this fixes #757 :)
Hope I did this right

(docs) Remove dollar sign ($) in front of terminal commands

---

Changelog.md
README.md

Spotted and removed a few more instances.
Ref. #757

Remove remaining dollar sign in docs

---

internals/generators/route/index.js
internals/generators/route/routeWithReducer.hbs

This adds a prompt to the route generator asking you if you want to use sagas for the route you're generating. It automatically detects if the component has a sagas file and sets the default accordingly.
Fixes #761.

Add saga prompt & detection on route generator.

---

internals/webpack/webpack.prod.babel.js

Prevent net::ERR_INSECURE_RESPONSE error. #669
More info at OfflinePlugin [#77 (comment)](https://github.com/NekR/offline-plugin/issues/77#issuecomment-234642483)

fix(OfflinePlugin): fixes #669

---

docs/general/faq.md

Closes #349
Please review @oliverturner

(docs) Add section about Node 0.12 to FAQ

---

app/app.js
internals/templates/app.js

Constrain eslint import/no-unresolved rule in app.js

---

docs/js/routing.md

fix route usage example

---

app/app.js
internals/generators/language/index.js
internals/generators/language/polyfill-intl-locale.hbs
internals/templates/app.js

In Safari browser,
when there is component using `<FormattedNumber />`
It will not get formatted and have some error in console.log
fixed it follow to this document in intl
https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack

Fix issue #791

---

docs/js/routing.md

Update routing.md for dynaic routes as per [#659](https://github.com/mxstbr/react-boilerplate/issues/659).

Document dynamic routes #659

---

docs/testing/component-testing.md
internals/templates/appContainer.js
internals/templates/languageProvider/languageProvider.js

@justingreenberg had a typo in ac1f6346535534e7061a8ba9b15a0f246a020a77
which broke the cleaned app. Closes #817

Fix React.Children

---

docs/README.md

The existing hyperlink didn't link to the app folder properly. :D

Updated README.md to fix hyperlink issue

---

internals/templates/asyncInjectors.js
internals/templates/asyncInjectors.test.js

updates asyncInjectors templates to latest 🍰

fix(internal): update asyncInjectors.js template

---

internals/templates/routes.js

@gihrig @mxstbr updates default route template to include injectors curried with instantiated store
ref: https://github.com/mxstbr/react-boilerplate/pull/812#issuecomment-237315789

chore(templates): include curried injectors after clean script

---

docs/js/routing.md

Just some formatting improvement.

Improve formatting.

---

README.md

[Thinkmill](http://thinkmill.com.au) has been supporting me to maintain this repo for the past half year, without them v3 would have never been finished. It's only fair they get some credit for it, so I've added their "Supported by Thinkmill" badge to the README!

Add "Supported by Thinkmill" badge

---

README.md
internals/scripts/setup.js
package.json

chore(dev branch): merge master into dev
Routine process to ensure that `dev` does not fall behind `master`.

chore(dev branch): merge master into dev

---

internals/config.js

hotfix(internals): version bump in config

---

internals/templates/app.js

Racing condition when polyfill intl in old browser (in templates)

---

docs/css/postcss.md

See https://github.com/mxstbr/react-boilerplate/pull/227#issuecomment-236163902

Explain how to add a new PostCSS plugin

---

internals/testing/test-bundler.js
internals/webpack/webpack.test.babel.js
package.json

PR for #924.
Remove `isparta` as it appears to be no longer used.

Remove isparta

---

docs/css/sass.md

fix(docs): Sass doc, build error fix

---

internals/webpack/webpack.dll.babel.js

https://github.com/mxstbr/react-boilerplate/issues/902#issuecomment-242961633

ISSUE-902 load webpack.base when build dll

---

internals/generators/container/index.js.hbs

Original PR here: https://github.com/mxstbr/react-boilerplate/pull/891
Issue to resolve here: https://github.com/mxstbr/react-boilerplate/issues/971

Pass null arg to connect in container template

---

docs/css/postcss.md
internals/webpack/webpack.base.babel.js
internals/webpack/webpack.dev.babel.js
internals/webpack/webpack.prod.babel.js

Since postcss config were the same in both dev and prod I moved them to base config
see #947

Deduplicated postcss webpack config

---

LICENSE.md

fix(license): Update license copyright to 2016

---

docs/general/README.md
package.json

Update `es2015` preset to `latest`, see issue #1013

Use babel latest preset

---

package.json

https://github.com/airbnb/javascript/issues/1088

HOTFIX fix airbnb dependencies

---

internals/webpack/webpack.base.babel.js

Fixes https://github.com/mxstbr/react-boilerplate/issues/1046
owners to license your work under the terms of the [MIT License](https://github.com/mxstbr/react-boilerplate/blob/master/LICENSE.md).

ISSUE-1046 fix entrypoint for dependency to use browser field first

---

internals/webpack/webpack.base.babel.js

fix stats webpack option to output analyze json correctly

---

internals/config.js
internals/scripts/clean.js
package.json

The file `app/translations/de.json` wasn't deleted after running `npm run clean`
See #1050

fix: delete de.json after npm run clean

---

package.json

Adds eslint-plugin-redux-saga linting rules. Closes #764. CC: @mxstbr 
owners to license your …

implement(#764): Add eslint-plugin-redux-saga

---

docs/general/faq.md

Add documentation to the FAQ about the F5/Ctrl+F5 AKA local caching issue.
See https://github.com/mxstbr/react-boilerplate/issues/852#issuecomment-252037351

FIX 852, 1074 - Add doc about local caching issue in the FAQ.

---

internals/scripts/analyze.js
internals/scripts/clean.js
internals/scripts/dependencies.js
internals/scripts/helpers/checkmark.js
internals/scripts/helpers/progress.js
internals/scripts/npmcheckversion.js
internals/scripts/pagespeed.js
internals/scripts/setup.js

This PR contains small changes of script files to make the scripts cleaner and easier to read. The changes are:
- Using `const` and `let` instead of `var`.
- Checking existence of callback function before calling it in `checkmark.js`
- Reusing addCheckMark in `clean.js`. 
- Adding semicolons in `dependencies.js`

Clean up code in script files

---

internals/scripts/analyze.js
internals/scripts/clean.js
internals/scripts/dependencies.js
internals/scripts/helpers/checkmark.js
internals/scripts/helpers/progress.js
internals/scripts/npmcheckversion.js
internals/scripts/pagespeed.js
internals/scripts/setup.js

Reverts mxstbr/react-boilerplate#775

Revert "Clean up code in script files"

---

docs/js/routing.md

See https://github.com/mxstbr/react-boilerplate/issues/1056#issuecomment-250952017

Added steps for setting up index routes in guide/documentation

---

README.md

Replace banner link in README.md

---

app/containers/HomePage/sagas.js
app/containers/HomePage/tests/sagas.test.js

Use takeLatest

---

app/containers/LanguageProvider/index.js
internals/templates/languageProvider/languageProvider.js

Add a key property to IntlProvider which persuades React that the component has been modified, so when we use changeLocale it automatically re-renders.

Add a key property to IntlProvider

---

yarn.lock

Yarn-detected updates, Oct 22.

Yarn-detected updates Oct 22

---

internals/webpack/webpack.base.babel.js

Namedmodulesplugin

---

docs/js/remove.md

fix broken MD syntax

---

internals/templates/store.js

shout out to @petemill for catching this
https://github.com/mxstbr/react-boilerplate/pull/406#issuecomment-256543228
@mxstbr maybe merge into master?

hotfix(templates): store parity/sync reducer HMR

---

appveyor.yml

Since we'll have 4 CI builds running in parallel, thought some caching might speed things up

Added node_modules caching for appveyor ci

---

app/containers/App/constants.js
app/i18n.js
app/translations/de.json
app/translations/en.json
internals/generators/language/format-translation-messages.hbs
internals/generators/language/index.js
internals/scripts/extract-intl.js
internals/templates/i18n.js

https://github.com/mxstbr/react-boilerplate/pull/391#issuecomment-236089492
There is some work need to be done.
This pull request assume `en` as a default message.
And set the constant in `App` container.
I'm not sure if it best practice, please review
https://github.com/mxstbr/react-boilerplate/pull/931/files#diff-0bdc92e05d8f3ab638aa855679db059eR25

Shrink translation messages files

---

internals/generators/container/test.js.hbs

Fixed #995 by importing specific container class

---

docs/general/deployment.md

Made changes to Step 3 per the discussion in #743, as well as some
grammar/formatting adjustments and an update to the buildpack version
mentioned in Step 2 (v91 is the latest stable)

feat(docs): Deployment docs update (#1177)

---

app/components/Toggle/index.js
app/containers/LocaleToggle/index.js

As requested by @mxstbr in [#1187 Comment](https://github.com/mxstbr/react-boilerplate/pull/1187#issuecomment-258374771).

fix(example): Fix i18n button not updating (#1187)

---

docs/general/faq.md

Keeping your project up-to-date with react-boilerplate can be difficult and there is *no recommended approach* at the moment. There is a long term goal to change this (see #1180), so this PR is more or less to document the official response to the common question "how to keep my project up-to-date or in sync with the boilerplate". Would love to hear feedback!
Also added a TOC as I feel this makes it much easier to navigate.

Faq staying updated with boilerplate

---

app/containers/LanguageProvider/reducer.js
app/translations/de.json
app/translations/en.json
internals/generators/language/app-locale.hbs
internals/generators/language/index.js
internals/templates/i18n.js
internals/templates/languageProvider/constants.js
internals/templates/languageProvider/reducer.js

https://github.com/mxstbr/react-boilerplate/issues/1191
There are some wrong regular expression.
Fixed in this pull request.
Also, set reducer to use DEFAULT_LANGUAGE for consistency.

HOTFIX-ISSUE#1191 npm run generate language is not properly created.

---

internals/webpack/webpack.base.babel.js

@samit4me 
Regarding the previously mistaken pull request (https://github.com/mxstbr/react-boilerplate/pull/1195), i am now making an updated one. And all tests do pass :)

modified webpack with new query object syntax

---

internals/generators/language/index.js

Resolves [#1234](https://github.com/mxstbr/react-boilerplate/issues/1234)

Prevent language duplication

---

package.json

In case you're interested in a hotfix to the master branch, @mxstbr

hotfix(deps): lock react-addons-test-utils

---

app/containers/HomePage/tests/sagas.test.js

I would love to see a more elegant solution, but as #1232 discusses, this seems to be the solution employed by the eslint-plugin-redux-saga project.
Resolves #1232

fix(HomePage): Saga effects should be yielded

---

package.json

- Exclude test files from test coverage as including them looks bad because of all the red and it actually, reduces overall stats.
- Added coverage threshold.

Test coverage updates

---

package.json
yarn.lock

Remove babel-jest expicit dependency

---

server/index.js

cross-env NODE_ENV=development node server
{ _: [] } <--- removed
Server started ! ✓

codeStyle(server): remove console.log causing server screen clutter

---

docs/general/commands.md
docs/general/deployment.md
docs/testing/component-testing.md
docs/testing/unit-testing.md

- Move from Mocha to Jest documentation
- Remove rewire docs and replace with Jest snapshot information.
This should address #1206!

Move to Jest Documentation

---

docs/README.md

Add 'Introduction' link to `docs/README.md` to make @KarandikarMihir 's excellent work available to users re: #1366

docs(toc): include link to new intro document

---

app/index.html

Fix #1435 comment

---

docs/general/deployment.md

Complete #1439 for AWS S3 bucket deployment.

Add AWS documentation to deployment.md

---

README.md
docs/general/introduction.md

Took @KarandikarMihir's amazing work of art from #1366 and cleaned it up just a little to get it ready for the big release.
It's now called the "Hitchhikers Guide to `react-boilerplate`" to make sure we avoid having full-on React beginners think we'll teach them React. Other than that it's mostly cosmetic changes related to Markdown formatting, there wasn't anything left @KarandikarMihir didn't touch upon!
Super impressive, can't wait to show this to the world!

Introduction cleanup

---

docs/general/introduction.md

Fix a broken link to redux-saga docs.
Fixes #1463

Fix a broken link to redux-saga docs.

---

docs/testing/component-testing.md
docs/testing/unit-testing.md

I noticed some minor flaws in the unit and component test docs.
- Code snippets were linted, unused imports removed und mising imports added.
- To give readers a complete overview of the test files described in the docs, I added them at the end of the relevant section.
- Also an link to the next doc was added at the end of component-testing
No code changes, no new tests.

[Doc] Improve unit test and component test documentation

---

app/components/Button/index.js
app/components/Img/index.js
docs/testing/component-testing.md
internals/templates/containers/App/index.js

Remove .react.js extensions

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE.md
README.md
app/components/ReposList/tests/index.test.js
app/containers/RepoListItem/tests/index.test.js
docs/README.md
docs/general/faq.md
docs/general/introduction.md
package.json

Cherry picks the commit from #1515 into `dev`. Let's ship this asap so the branches don't get out of date!
(need to "Rebase and merge" this one!)

Bring dev up to date with master

---

app/components/List/index.js
app/components/List/tests/index.test.js
package.json

fix(eslint): Enable rule react/no-array-index-key

---

internals/scripts/dependencies.js

Extending #1510 "fix(webpack) Make webpack less verbose" to install scripts.
Ref #1506

fix(dependencies.js): clean up console clutter for install scripts

---

docs/js/i18n.md

Fix typo i18n.md

---

package.json

This PR will sort the ESLint configuration alphabetically in `package.json`.

chore(package.json): sort ESLint config

---

docs/general/faq.md

A small grammatical fixup in faq.md

---

docs/general/commands.md

I find Chris Bateman'as visualizer to be more useful, especially given the number of dependencies this boilerplate has. Works with the same json stats format.
Be kind to code reviewers, please try to keep pull requests as small and focused as …

Add visualizer info

---

internals/scripts/clean.js

Nothing crazy. Just fixes #1781

Fix: Use local instance of shelljs

---

docs/general/introduction.md

Fixes  #1663. Thank you @nk1tz for your contribution. I just copied your changes.

Add missing word

---

app/components/ProgressBar/tests/ProgressBar.test.js
app/components/ProgressBar/tests/index.test.js
app/components/Toggle/tests/index.test.js
app/containers/FeaturePage/tests/index.test.js
app/containers/HomePage/tests/index.test.js
app/tests/store.test.js
package.json

- tests: removing global-styles.js from coverage collect
- tests(FeaturePage): testing shouldComponentUpdate function
- tests(HomePage): testing if username prop is missing
- tests(ProgressBar): testing when route is not changing
- tests(Toggle): adding tests for empty values prop
- tests(store): adding missing tests
- tests(ProgressBar): adding missing tests

Adding some tests

---

package.json
yarn.lock

I the project does not use this library anywhere
It can be removed

chore(deps): remove unusable deps sinon

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/general/commands.md
docs/general/introduction.md

@justingreenberg, @KarandikarMihir, I resolved the conflicts but don't know what's the best way to merge it, I can do that by activating "Allow merge commits" option temporarily, does that mean we'll have two merge commits? Or temporarily removing protection from `dev` and pushing commits directly.

chore(repo): Backport `master` to `dev`

---

app/index.html
package.json

A little different between `master` and `dev`, here i merge master into dev.

chore(repo): Sync dev with master

---

internals/config.js

Updated version string

---

docs/css/README.md

Find some unexpected character, remove it here.

fix(docs): Remove unexpected character in docs

---

app/components/Button/A.js
app/components/Button/StyledButton.js
app/components/Header/HeaderLink.js
app/components/LoadingIndicator/Circle.js
package.json
yarn.lock

It's a PR for #1830
Added and configured stylelint with config and processor for linting SC.
Fixed some linting errors.

Support stylelint for styled-components

---

docs/js/redux.md

Some people have asked for a login flow example before, and @tinavanschelt has a great example- so I reference that in the docs under Redux.
See #2031 
I requested review from a couple of new members, so whomever gets to it first 😄

Add login flow example reference in the docs

---

docs/general/introduction.md

Fixing a typo in introduction.md

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/general/introduction.md

fix(docs): link fixes in docs

---

docs/general/README.md

Just noticed a broken link when I was setting up a new project. Cheers!

Update styled components link

---

internals/generators/container/class.js.hbs
internals/generators/container/stateless.js.hbs

Fix the reducer key to inject must be consistent with the key used in selector to get state

fix(internals): Fix generator template of stateless component

---

docs/css/README.md
docs/general/introduction.md
docs/general/server-configs.md
docs/maintenance/dependency.md

This PR fixes some typos in the documentation.

docs: fix typos

---

package.json

Adds jest -watch / jest -o in package.json

---

package.json

Reverts react-boilerplate/react-boilerplate#2100
@blling please merge

Revert "Adds jest -watch / jest -o in package.json"

---

docs/general/introduction.md

Reverts react-boilerplate/react-boilerplate#2133

Revert "Correct a few typos"

---

README.md

Replaced highlighted text with link (LICENSE.md) in README.md

Added link for LICENSE.md

---

app/containers/LanguageProvider/tests/actions.test.js

Redid #2117 with dev as the base branch. Just a simple spelling mistake.

Spelling mistake fix

---

internals/scripts/clean.js
internals/scripts/generate-templates-for-linting.js

Fix few eslint errors

---

internals/scripts/setup.js

This PR fixes new repository initialisation mentioned in #2192 issue. It simply adds a process end to `gitInit()` callback.

Fix new repository setup

---

docs/js/i18n.md

Just a quick update of the docs-- seems IntlProvider was changed to LanguageProvider.

IntlProvider is now LanguageProvider

---

docs/general/editor.md

:wave: I don't think there's an issue for this or that one would be warranted. Happy to open one if that's preferred. 
The links to VS Code docs were outdated and there was a small typo so fixed it along the way.
Be kind to code reviewers, please …

Update links and fix typos in docs/general/editor.md

---

internals/generators/container/index.js.hbs

Fix container template not normalizing name

---

docs/forks/README.md

TypeScript fork added to forks readme. #2351

Forks readme updates

---

app/app.js
internals/templates/app.js

See https://github.com/react-boilerplate/react-boilerplate/pull/2403#issuecomment-432767838
Once again, with gusto. I had managed to horribly mutilate my commit history in the previous request 🤐

bootstrap initial state as plain javascript object

---

package-lock.json
package.json

Update package.json version to 3.7.0

---

package-lock.json
package.json

No time for a break!!
J/k. Wanted to undo the package-lock changes from #2410 that I missed when reviewing. Also took advantage of this to upgrade Webpack to 4.23.1

Undo package lock changes

---

internals/templates/app.js
package-lock.json
package.json

@gretzky The .htaccess fix from @ngtan is a non-trivial bug fix for anyone using apache. (Without the fix, the file created in build will be .htaccess.bin...) Should we release it straight to master? Feel free to merge this if you agree.

Fix .htaccess bug in template app

---

.github/issue-close-app.yml
CONTRIBUTING.md

Minor updates

---

internals/generators/component/test.js.hbs
internals/generators/container/stateless.js.hbs
internals/generators/container/test.js.hbs

Generate passing tests for components/containers

---

.github/issue-close-app.yml

The issue close bot is mistakenly closing issues that use the template. I'm assuming it's because it's case-sensitive. (The bot is looking for "Steps to Reproduce" but the Issue Template uses "Steps to reproduce".) Hopefully, this should fix it.

Fix for the issue close bot

---

.github/issue-close-app.yml

A cheeky little PR to update the lock bot message in the only place where it really matters.

Update lock bot message

---

app/utils/history.js
docs/general/deployment.md
internals/webpack/webpack.base.babel.js

Subfolder deployment

---

docs/general/deployment.md

Fixes #2517 - No longer advise setting Heroku `NPM_CONFIG_PRODUCTION=false` variable as Heroku installs dev dependencies by default; and prevents users from serving the app in development mode by accident.
Be kind to code reviewers, please try to keep pull …

Update Heroku deployment docs

---

docs/general/introduction.md
docs/general/server-configs.md

Just fixed some typos that were bothering me in the `general` docs.

fixed typos in general docs

---

internals/scripts/analyze.js

Just fixed import ordering, because eslint have an error
owners to license your work under …

Fixed import ordering

---

docs/general/README.md
docs/general/deployment.md

Adding documentation for deploying the boilerplate on AWS Elastic Beanstalk. 
Closes #2566  …

Adding documentation from #2566

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
README.md
docs/general/faq.md
docs/general/files.md

@gretzky, I think what was happening was some of the commits in master were also in dev but not all of them. So git/github were freaking out.
I created a new branch from the same point as master and rebased those commits on top of dev. Everything should be good now and we'll be able to merge dev into master when we're ready for a release.

Master changes back into dev

---

internals/generators/index.js

Fixing inconsistent build results on Appveyor
